theme: jekyll-theme-minimal
title: 落水石：随想与诗
description: 地上稀落的白痕, 是飞鸟经过的仅存见证, 他却带走了风
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
